language: php
sudo: required
php:
    - 7.4
    - 8.0
    - nightly
install:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction
script:
    - vendor/bin/phpcs --report=full --report-file=./report.txt -p ./src
    - vendor/bin/phpstan analyse -c phpstan.neon -l max src
jobs:
    allow_failures:
        -   php: 8.0
        -   php: nightly
