---
name: "Abstract Blog Theme"
author: "Rezo Zero"
copyright: "Rezo Zero"
themeDir: "AbstractBlogTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.22.0"
importFiles:
    roles: []
    groups: []
    settings:
        - "Resources/import/settings.rzt"
    nodetypes:
        - "Resources/import/node-type/Link.rzt"
    tags: []
    nodes: []
