---
name: "Abstract Blog Theme"
author: "Rezo Zero"
copyright: "Rezo Zero"
themeDir: "AbstractBlogTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "1.7.0"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes:
        - Resources/import/node-type/BlogFeedBlock.json
        - Resources/import/node-type/BlogPost.json
        - Resources/import/node-type/BlogPostContainer.json
    tags: []
    nodes: []
