---
name: "Abstract Blog Theme"
author: "Rezo Zero"
copyright: "Rezo Zero"
themeDir: "AbstractBlogTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.22.0"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes:
        - Resources/import/node-type/BlogFeedBlock.rzt
        - Resources/import/node-type/BlogPost.rzt
        - Resources/import/node-type/BlogPostContainer.rzt
    tags: []
    nodes: []
